#ifndef MY_IDA_H
# define MY_IDA_H

#include <ida.hpp>
#include <expr.hpp>

#if __cplusplus
 extern "C"
 {
#endif

extern funcset_t *RP_Funcs;

unsigned long NextAddr(long );
unsigned long SegByBase(long );
unsigned long GetOperandValue(long ,long );
unsigned long SegByName(char * );
void Del_dref(long ,long );
void SetSelector(long ,long );
unsigned long DbgByte(long );
unsigned long PrevFunction(long );
char * GetStrucComment(long ,long );
unsigned long SetSegmentAttr(long ,long ,long );
int OpStkvar(long ,long );
int DelHotkey(char * );
unsigned long GetEnumQty();
unsigned long SetStrucIdx(long ,long );
char * strfill(long ,long );
unsigned long GetPrevIndex(long ,long ,long );
unsigned long SelEnd();
unsigned long ord(char * );
int SetArrayFormat(long ,long ,long ,long );
unsigned long DfirstB(long );
unsigned long GetConstEnum(long );
unsigned long Rnext(long ,long );
unsigned long Til2Idb(long ,char * );
unsigned long Qword(long );
unsigned long GetEnum(char * );
char * GetConstName(long );
char * AltOp(long ,long );
unsigned long MakeCode(long );
char * GetLocalType(long ,long );
int Jump(long );
unsigned long NextFchunk(long );
unsigned long FindVoid(long ,long );
int PatchDword(long ,long );
char * LineA(long ,long );
unsigned long NextFunction(long );
int AddSeg(long ,long ,long ,long ,long ,long );
unsigned long SetMemberComment(long ,long ,char * ,long );
int SetArrayString(long ,long ,char * );
void DelSelector(long );
unsigned long Rfirst(long );
unsigned long GetConstByName(char * );
char * GuessType(long );
int SetColor(long ,long ,long );
unsigned long SetStatus(long );
unsigned long GetMemberQty(long );
unsigned long GetStrucIdByName(char * );
unsigned long AddStrucEx(long ,char * ,long );
char * GetTrueNameEx(long ,long );
void RefreshLists();
int AddSourceFile(long ,long ,char * );
int GenCallGdl(char * ,char * ,long );
unsigned long GetFchunkReferer(long ,long );
int SetProcessorType(char * ,long );
int SetFunctionEnd(long ,long );
char * AskIdent(char * ,char * );
unsigned long GetFixupTgtOff(long );
int ApplySig(char * );
void ChangeConfig(char * );
int SetEnumCmt(long ,char * ,long );
unsigned long RebaseProgram(long ,long );
unsigned long SetStorageType(long ,long ,long );
void SetFlags(long ,long );
void DelLineNumber(long );
unsigned long GetFixupTgtDispl(long );
unsigned long GetMaxLocalType();
unsigned long FindText(long ,long ,long ,long ,char * );
unsigned long FindBinary(long ,long ,char * );
int OpSign(long ,long );
char * GetString(long ,long ,long );
unsigned long PrevNotTail(long );
int SetBmaskName(long ,long ,char * );
int SetHashString(long ,char * ,char * );
int MakeData(long ,long ,long ,long );
int OpNumber(long ,long );
unsigned long AddEnum(long ,char * ,long );
unsigned long GetNextConst(long ,long ,long );
unsigned long GetEntryPoint(long );
int SetFchunkOwner(long ,long );
int DelSeg(long ,long );
int OpEnumEx(long ,long ,long ,long );
unsigned long GetLastConst(long ,long );
char * GetCurrentLine();
int OpOctal(long ,long );
char * GetEntryName(long );
int SetRegEx(long ,char * ,long ,long );
unsigned long GetStrucSize(long );
void SetManualInsn(long ,char * );
unsigned long GetSpDiff(long );
int OpChr(long ,long );
unsigned long Byte(long );
int SetSegDefReg(long ,char * ,long );
int PatchWord(long ,long );
int PatchByte(long ,long );
int SetLongPrm(long ,long );
int SetCharPrm(long ,long );
unsigned long AddHotkey(char * ,char * );
long GenerateFile(long ,long ,long ,long ,long );
int GenFuncGdl(char * ,char * ,long ,long ,long );
unsigned long GetColor(long ,long );
unsigned long GetCustomDataType(char * );
unsigned long PrevHead(long ,long );
char * CommentEx(long ,long );
unsigned long DbgDword(long );
int SaveBase(char * ,long );
int OpFloat(long ,long );
int MakeAlign(long ,long ,long );
char * NameEx(long ,long );
unsigned long NextSeg(long );
void MakeVar(long );
void DelEnum(long );
char * GetInputFilePath();
unsigned long AskAddr(long ,char * );
unsigned long writeshort(long ,long ,long );
unsigned long MK_FP(long ,long );
unsigned long GetCharPrm(long );
unsigned long IsUnion(long );
unsigned long FindImmediate(long ,long ,long );
unsigned long Rnext0(long ,long );
int AddUserStkPnt(long ,long );
unsigned long LocByName(char * );
int SetConstName(long ,char * );
int RunPlugin(char * ,long );
unsigned long readshort(long ,long );
unsigned long GetSegmentAttr(long ,long );
unsigned long GetConstValue(long );
unsigned long SetStrucComment(long ,char * ,long );
unsigned long PrevAddr(long );
char * GetFirstHashKey(long );
int SetShortPrm(long ,long );
int RecalcSpd(long );
void AutoMark2(long ,long ,long );
unsigned long GetNextFixupEA(long );
unsigned long GetFixupTgtSel(long );
int SetEnumWidth(long ,long );
unsigned long NextFuncFchunk(long ,long );
unsigned long GetArrayId(char * );
int SetFunctionAttr(long ,long ,long );
int RenameArray(long ,char * );
unsigned long AskLong(long ,char * );
int MakeFunction(long ,long );
int OpHex(long ,long );
void ExtLinA(long ,long ,char * );
int OpNot(long ,long );
int SetType(long ,char * );
unsigned long GetHashLong(long ,char * );
unsigned long GetMemberSize(long ,long );
unsigned long AskYN(long ,char * );
unsigned long FirstSeg();
int SetHashLong(long ,char * ,long );
int MakeComm(long ,char * );
unsigned long readlong(long ,long );
int SetFchunkAttr(long ,long ,long );
char * GetConstCmt(long ,long );
void Wait();
unsigned long AddConstEx(long ,char * ,long ,long );
unsigned long GetSpd(long );
unsigned long Dfirst(long );
unsigned long writestr(long ,char * );
void SetFixup(long ,long ,long ,long ,long );
void Refresh();
int RenameEntryPoint(long ,char * );
int MakeLocal(long ,long ,char * ,char * );
unsigned long Dnext(long ,long );
unsigned long GetFrameSize(long );
int MakeStr(long ,long );
unsigned long FindUnexplored(long ,long );
char * LineB(long ,long );
char * Demangle(char * ,long );
unsigned long NextNotTail(long );
unsigned long GetConstBmask(long );
int OpOffEx(long ,long ,long ,long ,long ,long );
char * readstr(long );
char * GetOpnd(long ,long );
void MakeUnknown(long ,long ,long );
unsigned long GetPrevConst(long ,long ,long );
void MakeUnkn(long ,long );
unsigned long SelStart();
unsigned long ExecIDC(char * );
unsigned long SetMemberName(long ,long ,char * );
int SetConstCmt(long ,char * ,long );
void DeleteArray(long );
char * GetMnem(long );
unsigned long FindCode(long ,long );
unsigned long xtol(char * );
int EndTypeUpdating(long );
unsigned long DbgWord(long );
unsigned long GetStrucIdx(long );
int DelStruc(long );
unsigned long GetBmaskCmt(long ,long ,long );
unsigned long GetMemberOffset(long ,char * );
void AddCodeXref(long ,long ,long );
unsigned long PrevFchunk(long );
int OpSeg(long ,long );
unsigned long ItemEnd(long );
unsigned long GetLastBmask(long );
unsigned long NextHead(long ,long );
unsigned long GetNextBmask(long ,long );
unsigned long RnextB(long ,long );
unsigned long GetFunctionAttr(long ,long );
unsigned long GetPrevBmask(long ,long );
unsigned long GetFirstBmask(long );
char * GetManualInsn(long );
int DelHiddenArea(long );
unsigned long GetEnumWidth(long );
unsigned long ProcessUiAction(char * ,long );
int SetSpDiff(long ,long );
unsigned long Rfirst0(long );
unsigned long GetBmaskName(long ,long );
int SetEnumBf(long ,long );
unsigned long GetStrucId(long );
unsigned long ItemHead(long );
unsigned long GetPrevStrucIdx(long );
unsigned long ScreenEA();
int DelHashElement(long ,char * );
char * GetEnumName(long );
char * GetDisasm(long );
unsigned long DbgQword(long );
unsigned long RfirstB0(long );
unsigned long GetOpType(long ,long );
unsigned long GetFixupTgtType(long );
char * GetFunctionCmt(long ,long );
char * GetMemberName(long ,long );
unsigned long GetStrucPrevOff(long ,long );
char * GetMemberComment(long ,long ,long );
unsigned long GetLastIndex(long ,long );
void DelExtLnB(long ,long );
unsigned long GetOriginalByte(long );
int SetArrayLong(long ,long ,long );
char * GetLocalTypeName(long );
unsigned long GetShortPrm(long );
unsigned long Dword(long );
void SetLineNumber(long ,long );
unsigned long RfirstB(long );
void SetFunctionCmt(long ,char * ,long );
char * GetMarkComment(long );
unsigned long FindExplored(long ,long );
unsigned long MakeFrame(long ,long ,long ,long );
char * DbgRead(long ,long );
int OpBinary(long ,long );
char * GetInputFile();
unsigned long LocByNameEx(long ,char * );
char * GetIdbPath();
char * GetPrevHashKey(long ,char * );
unsigned long GetFirstStrucIdx();
unsigned long RnextB0(long ,long );
unsigned long XrefType();
unsigned long FindSelector(long );
unsigned long GetStrucQty();
unsigned long GetLastStrucIdx();
char * AskStr(char * ,char * );
void SetInputFilePath(char * );
void SetTargetAssembler(long );
int SetEnumName(long ,char * );
int MakeStructEx(long ,long ,char * );
int OpDecimal(long ,long );
unsigned long writelong(long ,long ,long );
unsigned long GetFirstIndex(long ,long );
unsigned long ParseTypes(char * ,long );
char * Atoa(long );
unsigned long Word(long );
int BeginTypeUpdating(long );
int IsBitfield(long );
int SetSegBounds(long ,long ,long ,long );
unsigned long SetStrucName(long ,char * );
int OpOff(long ,long ,long );
char * GetEnumCmt(long ,long );
char * GetHashString(long ,char * );
char * GetType(long );
int SetLocalType(long ,char * ,long );
unsigned long FirstFuncFchunk(long );
unsigned long MoveSegm(long ,long ,long );
unsigned long ChooseFunction(char * );
char * AskFile(long ,char * ,char * );
char * GetFuncOffset(long );
unsigned long DnextB(long ,long );
unsigned long GetLineNumber(long );
unsigned long FindFuncEnd(long );
unsigned long ItemSize(long );
unsigned long GetReg(long ,char * );
int SetSegClass(long ,char * );
char * SegName(long );
int PatchDbgByte(long ,long );
unsigned long GetNextIndex(long ,long ,long );
unsigned long GetFchunkAttr(long ,long );
int OpHigh(long ,long ,long );
int OpStroffEx(long ,long ,long ,long );
int LoadTil(char * );
unsigned long GetMinSpd(long );
char * GetInputMD5();
void Add_dref(long ,long ,long );
unsigned long GetMemberStrId(long ,long );
unsigned long GetPrevFixupEA(long );
int SetSegAddressing(long ,long );
int DelFunction(long );
unsigned long GetCustomDataFormat(char * );
int MakeRptCmt(long ,char * );
int RenameSeg(long ,char * );
unsigned long IdbByte(long );
int RemoveFchunk(long ,long );
unsigned long DelStrucMember(long ,long );
unsigned long GetFirstMember(long );
unsigned long SetBmaskCmt(long ,long ,char * ,long );
int MakeNameEx(long ,char * ,long );
unsigned long AskSelector(long );
unsigned long GetLastMember(long );
int SetXML(char * ,char * ,char * );
char * GetStrucName(long );
int SetHiddenArea(long ,long );
int savefile(long ,long ,long ,long );
int MakeArray(long ,long );
char * GetIdaDirectory();
int AppendFchunk(long ,long ,long );
unsigned long AskSeg(long ,char * );
unsigned long GetMemberFlag(long ,long );
unsigned long GetStrucNextOff(long ,long );
int HideArea(long ,long ,char * ,char * ,char * ,long );
char * GetFunctionName(long );
unsigned long GetConstEx(long ,long ,long ,long );
unsigned long GetMarkedPos(long );
unsigned long GetnEnum(long );
int AddEntryPoint(long ,long ,char * ,long );
unsigned long CreateArray(char * );
int DelArrayElement(long ,long ,long );
unsigned long GetStringType(long );
void DelExtLnA(long ,long );
void MarkPosition(long ,long ,long ,long ,long ,char * );
char * GetNextHashKey(long ,char * );
unsigned long GetEnumFlag(long );
unsigned long GetEnumSize(long );
unsigned long GetLongPrm(long );
unsigned long Exec(char * );
char * GetSourceFile(long );
unsigned long AnalyzeArea(long ,long );
void DeleteAll();
int DelConstEx(long ,long ,long ,long );
unsigned long GetFirstConst(long ,long );
void Exit(long );
char * GetLastHashKey(long );
unsigned long Batch(long );
void AutoUnmark(long ,long ,long );
unsigned long DelCodeXref(long ,long ,long );
void ExtLinB(long ,long ,char * );
int DelSourceFile(long );
int OpAlt(long ,long ,char * );
int SetEnumFlag(long ,long );
unsigned long GetNextStrucIdx(long );
unsigned long GetFlags(long );
void DelFixup(long );
unsigned long GetEnumIdx(long );
unsigned long FindData(long ,long );
int SetEnumIdx(long ,long );
unsigned long GetEntryOrdinal(long );
unsigned long GetEntryPointQty();
unsigned long DbgWrite(long ,char * );
extern int IDA_version(void);
extern char *loader_name(void);
extern int load_ids(char *);
extern void save_idb(void);
extern int is_debugged(void);
extern long GetOriginalWord(long);
extern long GetOriginalDword(long);
extern void MakeUnknRange(long, long, int);
extern int IsPublicName(long);
extern void MakeNamePublic(long);
extern void MakeNameNonPublic(long);
extern void HideName(long);
extern void ShowName(long);
extern char *IdpName(void);
extern int func_qty(void);
extern int func_n(int);

#if __cplusplus
 };
#endif

#endif /* MY_IDA_H */
